# PIAIC Q2 CLASS 1

In [1]:
%time
a = [1,2,3,4,5,6,7,8,9,10]
b = []
for num in a:
    b.append(num * 5)
print(b)

Wall time: 0 ns
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [2]:
%time
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a * 5 #no requirement of loop 
#ek no se multiply kra pura number vectorize form mein hogya

Wall time: 0 ns


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [3]:
numpyArray = np.array([22,44,55,66])
print(numpyArray)
type(numpyArray)
#also can be of 0 dimension

[22 44 55 66]


numpy.ndarray

In [4]:
numpyArray = np.array([22,44,55,66],dtype = "int")
print(numpyArray)
print(type(numpyArray))

"""OR"""

numpyArray = np.array([22,44,55,66],dtype = "float32")  #32 is no of bits
print(numpyArray)
print(type(numpyArray))

#if bit exceed from 32 then it will give an error

[22 44 55 66]
<class 'numpy.ndarray'>
[22. 44. 55. 66.]
<class 'numpy.ndarray'>


In [5]:
numpyArray = np.array([22,44.5,55,66])
#if any one is decimal then the whle array wwill be in decimal
print(numpyArray)
type(numpyArray)

[22.  44.5 55.  66. ]


numpy.ndarray

In [6]:
numpyArray = np.array([22,44,55,66], dtype = np.int8) 
#no need to pass the string if u are using np. no difference in str or simple
print(numpyArray)
type(numpyArray)

[22 44 55 66]


numpy.ndarray

In [7]:
randomArray = np.random.randint(10)
randomArray

9

In [8]:
randomArray = np.random.randn(10) * 100
randomArray

array([-155.65061993,    1.22252404,   30.68104365,   57.70143465,
       -134.93785156,  161.1696245 ,  116.95757582,   27.49608595,
         -2.48992302,    5.63208205])

In [9]:
#to check the dimension
randomArray.ndim

1

In [10]:
#row and coloumn
randomArray.shape

(10,)

array ---> vector
matix ---> tensor

In [11]:
twoD = np.array([[1,2,3],[3,4,5],[6,7,8],[9,10,11]])
print(twoD)
twoD.shape

[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


(4, 3)

In [12]:
zeroD = np.array(100)
zeroD.ndim

0

In [13]:
miscD = np.array([[99]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)
miscD1 = np.array([[[99]]])
print(miscD1)
print(miscD1.ndim)
print(miscD1.shape)
miscD2 = np.array([[[[99]]]])
print(miscD2)
print(miscD2.ndim)
print(miscD2.shape)

[[99]]
2
(1, 1)
[[[99]]]
3
(1, 1, 1)
[[[[99]]]]
4
(1, 1, 1, 1)


In [14]:
a = np.arange(10).reshape(5,2)
print(a)
b = np.arange(12).reshape(4,3)
print(b)
c = np.arange(12)
print(c)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
#flat har dimension ko seedha krega 1d mein to behtr hai k reshape use krein

In [16]:
# ravel flat krdeta hai
flat = np.ravel(b)
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
f = np.arange(36).reshape(6,6)
f

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
D = f.reshape(3,3,4)
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [19]:
tD = f.reshape(6,6)
tD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [20]:
threeD = np.array([[[[1,2,3],[4,5,6],[7,8,9]],[[3,6,8],[8,7,6],[9,8,7]]]])
threeD

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[3, 6, 8],
         [8, 7, 6],
         [9, 8, 7]]]])

In [21]:
[[[],[],[]]   ,  [[],[],[]]   , [[],[],[]]]

[[[], [], []], [[], [], []], [[], [], []]]

In [22]:
#shape same to do tensor add hskti hain

In [23]:
threeD / threeD

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [24]:
threeD + threeD #mirror addition

array([[[[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]],

        [[ 6, 12, 16],
         [16, 14, 12],
         [18, 16, 14]]]])

In [25]:
m1 = np.arange(12).reshape(4,3)

In [26]:
m2 = np.random.randn(16).reshape(4,4)

In [27]:
#m1 + m2 #shape should be same  #error

In [28]:
 #multiplication
#first check k multiply ho bh skta k nh
#(2,3) (2,3)

In [29]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [30]:
#multiplication
m1 @ m3 # @ matrix multiply, * siimple mirror multiply

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [31]:
print(np.dot(m1,m3))
print(m1.dot(m3))

[[ 30  33  36  39  42  45]
 [ 84  96 108 120 132 144]
 [138 159 180 201 222 243]
 [192 222 252 282 312 342]]
[[ 30  33  36  39  42  45]
 [ 84  96 108 120 132 144]
 [138 159 180 201 222 243]
 [192 222 252 282 312 342]]


In [32]:
zeeeeros = np.zeros(4,dtype = "int8")
zeeeeros

array([0, 0, 0, 0], dtype=int8)

In [33]:
zeeeeros = np.zeros((4,5),dtype = "int8")
zeeeeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [34]:
# onesss = np.ones((5,5),dtype = "int8") #agr hm chahe kk drype na print ho
onesss = np.ones((5,5))
onesss

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
onesss * 50

array([[50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.]])

In [36]:
fulll = np.full((4,4),100)
fulll

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [37]:
emptyyy = np.empty((4,4,4)) #empty zero hi laenge
emptyyy

array([[[1.09188508e-321, 0.00000000e+000, 3.78576700e-270,
         0.00000000e+000],
        [8.09477154e-320, 1.32625749e-315, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+0

In [38]:
#book page 100

In [39]:
like = np.zeros_like(m3)
print(m3)
print(like)# like copies shape and datatype 
#zero like nad one like

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [40]:
i = np.eye(5,5)
i
#identity matrix (diagnol pr 1 and determinant bhi 1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
j = i.astype("int") 
j
#shape wohi rhegi only datatype changed

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Basic indexing and slicing


In [42]:
alist = [99,77,55,33,11]

In [43]:
#column and row zero se start hti hai

In [44]:
#twod
tDarray = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [45]:
tDarray[3,2] #rrow 3 coloumn 2

20

In [46]:
tDarray[3][2]

20

In [47]:
#tDarray[row,column]
#tDarray[start:end , start:end]
tDarray[2:5 , 1:4]

#agr 2d hai to slice krk bhi 2d aegi

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [48]:
tDarray[5:,3:4] #slicing se wohi matrix ata hai

array([[33]])

In [49]:
tDarray[1:2 , 2:5]

array([[ 8,  9, 10]])